# Generated by Django 4.1.7 on 2023-04-07 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FYPAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examinationType', models.CharField(max_length=30)),
                ('examinationName', models.CharField(max_length=30)),
                ('semeter', models.IntegerField()),
                ('examDuration', models.TimeField()),
                ('examFullmark', models.IntegerField()),
                ('examinationDescription', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.course')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.masomo')),
                ('questionChoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.questionchoice')),
                ('questionSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.questionsection')),
            ],
        ),
        migrations.CreateModel(
            name='SavedExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mtihani.exam')),
                ('questionChoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.questionchoice')),
                ('questionLong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.questionlongterm')),
                ('questionShort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.questionshortterm')),
            ],
        ),
    ]
