# Generated by Django 4.1.7 on 2023-04-07 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FYPAPP', '0001_initial'),
        ('mtihani', '0003_exam_questionlong_exam_questionshort_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='questionShort',
        ),
        migrations.RemoveField(
            model_name='savedexam',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='savedexam',
            name='questionChoice',
        ),
        migrations.RemoveField(
            model_name='savedexam',
            name='questionLong',
        ),
        migrations.RemoveField(
            model_name='savedexam',
            name='questionShort',
        ),
        migrations.AddField(
            model_name='savedexam',
            name='mtihani',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='questionChoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.questionshortterm'),
        ),
    ]
