# Generated by Django 4.1.7 on 2023-04-09 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtihani', '0004_remove_exam_questionshort_remove_savedexam_exam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='course',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='examDuration',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='examFullmark',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='examinationDescription',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='examinationName',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='examinationType',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='module',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='questionSection',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='semeter',
        ),
    ]
