# Generated by Django 4.1.7 on 2023-04-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtihani', '0006_examquestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='questionChoice',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='questionLong',
        ),
        migrations.AddField(
            model_name='exam',
            name='examinationName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
