# Generated by Django 4.1.7 on 2023-04-09 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FYPAPP', '0001_initial'),
        ('mtihani', '0007_remove_exam_questionchoice_remove_exam_questionlong_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.course'),
        ),
        migrations.AddField(
            model_name='exam',
            name='examDuration',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='examFullmark',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='examinationDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='examinationType',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.masomo'),
        ),
        migrations.AddField(
            model_name='exam',
            name='questionChoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.questionshortterm'),
        ),
        migrations.AddField(
            model_name='exam',
            name='questionLong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.questionlongterm'),
        ),
        migrations.AddField(
            model_name='exam',
            name='questionSection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.questionsection'),
        ),
        migrations.AddField(
            model_name='exam',
            name='semeter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
