# Generated by Django 4.1.7 on 2023-04-11 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FYPAPP', '0001_initial'),
        ('mtihani', '0008_exam_course_exam_examduration_exam_examfullmark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mtihani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semeter', models.IntegerField(blank=True, null=True)),
                ('exam_name', models.CharField(max_length=50)),
                ('num_questions', models.IntegerField()),
                ('num_shortquestions', models.IntegerField()),
                ('num_longquestions', models.IntegerField()),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.course')),
            ],
        ),
        migrations.DeleteModel(
            name='ExamQuestion',
        ),
    ]
