# Generated by Django 4.1.7 on 2023-04-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtihani', '0011_mtihani_modulecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtihani',
            name='examdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='mtihani',
            name='examtime',
            field=models.TimeField(null=True),
        ),
    ]
