# Generated by Django 4.1.7 on 2023-04-11 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtihani', '0012_mtihani_examdate_mtihani_examtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mtihani',
            name='examdate',
        ),
        migrations.RemoveField(
            model_name='mtihani',
            name='examtime',
        ),
    ]
