# Generated by Django 4.1.7 on 2023-04-11 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtihani', '0014_mtihani_examdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mtihani',
            name='examdate',
        ),
    ]
