# Generated by Django 4.1.7 on 2023-04-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtihani', '0015_remove_mtihani_examdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtihani',
            name='examdate',
            field=models.DateField(null=True),
        ),
    ]
