# Generated by Django 4.1.7 on 2023-04-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtihani', '0016_mtihani_examdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='mtihani',
            name='examinationDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
