# Generated by Django 4.1.7 on 2023-04-07 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=30)),
                ('courseCode', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Masomo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleName', models.CharField(max_length=30)),
                ('moduleCode', models.CharField(max_length=30)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.course')),
            ],
        ),
        migrations.CreateModel(
            name='QCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionType', models.CharField(blank=True, choices=[('multichoice Questions', 'multichoice Questions'), ('short answers Questions', 'short answers Questions'), ('long answers Questions', 'long answers Questions')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionsection', models.CharField(choices=[('YES', 'YES'), ('NO', ' NO')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questiontype', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicNumber', models.IntegerField()),
                ('topicName', models.CharField(max_length=30)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.masomo')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionShortterm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=10)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.qcategory')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionLongTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.qcategory')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=50)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.qcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionLevel', models.CharField(choices=[('Normal', 'Normal'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=30, null=True)),
                ('questionText', models.TextField()),
                ('questionType', models.ForeignKey(default='multichoice_Questions', on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.qcategory')),
                ('somo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.masomo')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.topic')),
            ],
        ),
    ]
