# Generated by Django 4.1.7 on 2023-04-26 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FYPAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionchoice',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.topic'),
        ),
        migrations.AddField(
            model_name='questionlongterm',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.topic'),
        ),
        migrations.AddField(
            model_name='questionshortterm',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FYPAPP.topic'),
        ),
        migrations.AlterField(
            model_name='questionchoice',
            name='answer',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='questionchoice',
            name='option1',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='questionchoice',
            name='option2',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='questionchoice',
            name='option3',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='questionchoice',
            name='option4',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='questionchoice',
            name='question',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='questionshortterm',
            name='answer',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='questionshortterm',
            name='question',
            field=models.TextField(max_length=100),
        ),
    ]
